<?php
/**
 * Copyright © eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php $blockWrapper = $block->getWrapper(); ?>
<?php $blockWrapper->setObject($block); ?>

<?php $productMetadataHelper = $this->helper(\Ecombricks\Common\Helper\ProductMetadata::class); ?>
<div class="paypal-review view">
    <div class="block block-order-details-view">
        <div class="block-content">
            <?php if ($block->getShippingAddress()): ?>
                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                    </strong>
                    <div class="box-content">
                        <form method="post" id="shipping-method-form" action="<?= $block->escapeUrl($block->getShippingMethodSubmitUrl()) ?>" class="form">
                            
                            <!-- Inventory Begin -->
                            <?php if ($block->canEditShippingMethod()): ?>
                            <?php $shippingAddress = $block->getShippingAddress(); ?>
                            <?php $groupedShippingRates = $shippingAddress->getGroupedAllShippingRates(); ?>
                            <?php if (!empty($groupedShippingRates)): ?>
                                <div class="field shipping required">
                                    <?php foreach ($blockWrapper->getSourceCodes($shippingAddress) as $sourceCode) : ?>
                                    <?php $sourceShippingRates = !empty($groupedShippingRates[$sourceCode]) ? $groupedShippingRates[$sourceCode] : []; ?>
                                    <?php $sourceShippingMethod = $blockWrapper->getShippingMethod($shippingAddress, (string) $sourceCode); ?>
                                    <dl class="source">
                                        <dt class="source-info">
                                            <span class="source-name"><?= $block->escapeHtml($blockWrapper->getSourceName((string) $sourceCode)) ?></span>
                                        </dt>
                                        <dd class="source-shipping-method">
                                            <select name="shipping_method[<?= $sourceCode ?>]" id="shipping_method_<?= $sourceCode ?>" data-source="true" data-source-code="<?= $sourceCode ?>" class="shipping-method required-entry">
                                                <?php if (!$sourceShippingMethod) : ?>
                                                <option value=""><?= $block->escapeHtml(__('Please select a shipping method...')) ?></option>
                                                <?php endif; ?>
                                                <?php foreach ($sourceShippingRates as $carrierCode => $carrierShippingRates) : ?>
                                                <optgroup label="<?= $block->escapeHtml($blockWrapper->getSourceCarrierName((string) $sourceCode, $carrierCode)) ?>" style="font-style: normal;">
                                                    <?php foreach ($carrierShippingRates as $shippingRate) : ?>
                                                    <?php $selectedAttribute = ($sourceShippingMethod === $shippingRate->getCode()) ? ' selected="selected"' : '' ?>
                                                    <option value="<?= $block->escapeHtml($block->renderShippingRateValue($shippingRate)) ?>"<?= $selectedAttribute ?>>
                                                    <?= $block->renderShippingRateOption($shippingRate) ?>
                                                    </option>
                                                    <?php endforeach; ?>
                                                </optgroup>
                                                <?php endforeach; ?>
                                            </select>
                                        </dd>
                                    </dl>
                                    <?php endforeach; ?>
                                </div>
                                <div class="actions-toolbar">
                                    <div class="primary">
                                        <button id="update-shipping-method-submit" type="submit" class="action update primary">
                                            <span><?= $block->escapeHtml(__('Update Shipping Method')) ?></span>
                                        </button>
                                    </div>
                                </div>
                            <?php else: ?>
                            <p><?= $block->escapeHtml(__('Sorry, no quotes are available for this order right now.')); ?></p>
                            <?php endif; ?>
                            <?php else: ?>
                            <?php foreach ($blockWrapper->getSourceCodes($shippingAddress) as $sourceCode) : ?>
                            <?php $sourceShippingMethod = $blockWrapper->getShippingMethod($shippingAddress, $sourceCode); ?>
                            <?php $currentSourceShippingRate = $blockWrapper->getShippingRateByCode($shippingAddress, $sourceCode, $sourceShippingMethod) ?>
                            <dl class="source">
                                <dt class="source-info">
                                    <span class="source-name"><?= $block->escapeHtml($blockWrapper->getSourceName($sourceCode)) ?></span>
                                </dt>
                                <dd class="source-shipping-method">
                                    <strong><?= $block->renderShippingRateOption($currentSourceShippingRate) ?></strong>
                                </dd>
                            </dl>
                            <?php endforeach; ?>
                            <?php endif; ?>
                            <!-- Inventory End -->
                                
                        </form>
                    </div>
                </div>
                <div class="box box-order-shipping-address">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    </strong>
                    <div class="box-content">
                        <address>
                            <?= $block->escapeHtml(
                                $block->renderAddress($block->getShippingAddress()),
                                ['br']
                            );?>
                        </address>
                    </div>
                    <?php if ($block->getCanEditShippingAddress()): ?>
                        <div class="box-actions">
                            <a href="<?= $block->escapeUrl($block->getEditUrl()) ?>" class="action edit">
                                <span><?= $block->escapeHtml(__('Edit')) ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <div class="box box-order-billing-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Payment Method')) ?></span></strong>
                <div class="box-content">
                    <?= $block->escapeHtml($block->getPaymentMethodTitle()) ?><br>
                    <?= $block->escapeHtml($block->getEmail()) ?> <br>
                    <img src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/pp-acceptance-medium.png"
                         alt="<?= $block->escapeHtml(__('Buy now with PayPal')) ?>"/>
                </div>
            <?php if ($block->getEditUrl()): ?>
                <div class="box-actions">
                    <a href="<?= $block->escapeUrl($block->getEditUrl()) ?>" class="action edit">
                        <span><?= $block->escapeHtml(__('Edit Payment Information')) ?></span>
                    </a>
                </div>
            <?php endif ?>
            </div>
        </div>
    </div>

    <div class="paypal-review-discount">
        <?= $block->getChildHtml('paypal.additional.actions') ?>
    </div>

    <div class="paypal-review-items">
        <div class="paypal-review-title">
            <strong><?= $block->escapeHtml(__('Items in Your Shopping Cart')) ?></strong>
            <a href="<?= $block->escapeUrl($block->getUrl('checkout/cart')) ?>" class="action edit">
                <span><?= $block->escapeHtml(__('Edit Shopping Cart')) ?></span>
            </a>
        </div>

        <?= $block->getChildHtml('details') ?>

        <form method="post" id="order-review-form" action="<?= $block->escapeUrl($block->getPlaceOrderUrl()) ?>"
              class="form order-review-form">
            <?= $block->getChildHtml('agreements') ?>
            <div class="actions-toolbar" id="review-buttons-container">
                <div class="primary">
                    <button type="button" id="review-button" class="action checkout primary"
                            value="<?= $block->escapeHtml(__('Place Order')) ?>">
                        <span><?= $block->escapeHtml(__('Place Order')) ?></span>
                    </button>
                    <button type="button" id="review-submit" class="action checkout primary"
                            value="<?= $block->escapeHtml(__('Place Order')) ?>">
                        <span><?= $block->escapeHtml(__('Place Order')) ?></span>
                    </button>
                </div>
                <?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
                <span class="please-wait load indicator" id="review-please-wait" data-text="<?= $block->escapeHtml(__('Submitting order information...')) ?>">
                   <span><?= $block->escapeHtml(__('Submitting order information...')) ?></span>
                </span>
                <?= $secureRenderer->renderStyleAsTag("display: none;", 'span#review-please-wait')?>
                <?php else : ?>
                <span class="please-wait load indicator" id="review-please-wait" style="display: none;" data-text="<?= $block->escapeHtml(__('Submitting order information...')) ?>">
                   <span><?= $block->escapeHtml(__('Submitting order information...')) ?></span>
                </span>
                <?php endif; ?>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#order-review-form": {
            "validation": {},
            "orderReview": {
                "shippingSubmitFormSelector": "#shipping-method-form",
                "shippingSelector": ".shipping-method",
                "shippingMethodUpdateUrl": "<?= $block->escapeUrl($block->getUpdateShippingMethodsUrl()) ?>",
                "isAjax": <?= $block->getUseAjax() ? 'true' : 'false' ?>,
                "canEditShippingMethod": <?= $block->canEditShippingMethod() ? 'true' : 'false' ?>
            }
        }
    }
</script>