    <meta property="og:type" content="product"/>
    <meta property="og:title"
          content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getName())) ?>"/>
    <meta property="og:image"
          content="<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>"/>
    <meta property="og:description"
          content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getShortDescription())) ?>"/>
    <meta property="og:url" content="<?= $block->escapeUrl($block->getProduct()->getProductUrl()) ?>"/>
<?php
    $isShow = 1;
    if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
        <?php
        $callforHelper = $this->helper('Meetanshi\Callforprice\Helper\Data');
        if ($callforHelper->isEnabled()) {
            if ($callforHelper->isEnableFor() == 'global') {
                if (!$callforHelper->isAllowCustomerGroups()) {
                    $isShow = 0;
                } elseif ($callforHelper->isAllowCustomerGroups()) {
                    $customerGroupIds = $callforHelper->showCustomerGroups();
                    if ($customerGroupIds) {
                        $isShow = 0;
                    } else {
                        $isShow = 1;
                    }
                }
            } elseif ($callforHelper->isEnableFor() != 'product') {
                if ($callforHelper->isAllowCategories() && !$callforHelper->isAllowCustomerGroups()) {
                    $showInCategory = $callforHelper->showPrdCategories($block->getProduct()->getId());
                    if ($showInCategory) {
                        $isShow = 0;
                    } else {
                        $isShow = 1;
                    }
                } elseif ($callforHelper->isAllowCustomerGroups() && !$callforHelper->isAllowCategories()) {
                    $customerGroupIds = $callforHelper->showCustomerGroups();
                    if ($customerGroupIds) {
                        $isShow = 0;
                    } else {
                        $isShow = 1;
                    }
                } elseif ($callforHelper->isAllowCustomerGroups() && $callforHelper->isAllowCategories()) {
                    $showInCategory = $callforHelper->showPrdCategories($block->getProduct()->getId());
                    $customerGroupIds = $callforHelper->showCustomerGroups();
                    if ($customerGroupIds && $showInCategory) {
                        $isShow = 0;
                    } else {
                        $isShow = 1;
                    }
                } else {
                    $isShow = 1;
                }
            } else {
                $callForText = $callforHelper->getProductText($block->getProduct()->getId());
                if ($callforHelper->isAllowCustomerGroups() && $callForText) {
                    $customerGroupIds = $callforHelper->showCustomerGroups();
                    if ($customerGroupIds && $callForText) {
                        $isShow = 0;
                    } else {
                        $isShow = 1;
                    }
                } elseif (!$callforHelper->isAllowCustomerGroups() && $callForText) {
                    if ($callforHelper->getProductText($block->getProduct()->getId())) {
                        $isShow = 0;
                    } else {
                        $isShow = 1;
                    }
                } else {
                    $isShow = 1;
                }
            }
        } else {
            $isShow = 1;
        }
        ?>
        <?php if ($isShow): ?>
        <meta property="product:price:amount" content="<?= /* @escapeNotVerified */
        $priceAmount ?>"/>
            <?= $block->getChildHtml('meta.currency') ?>
    <?php endif; ?>
    <?php endif; ?>
