<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_FacebookShop
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-facebookshop-buttons-container">
    <button id="<?= /* @noEscape */ $block->getId() ?>" onclick="return false;">
        <span><span><span><?= /* @noEscape */ $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "generateCsv": {"generateCsvUrl":"<?= /* @noEscape */ $block->getAjaxCheckUrl() ?>"}
        }
    }
</script>
