<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Google Page Speed Optimizer Base for Magento 2
 */
/** @var \Amasty\PageSpeedOptimizer\Block\Adminhtml\Settings\ServerPushInfo $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="amoptimizer-notice-container">
    <?= $escaper->escapeHtml(
        __(
            'The server needs to be configured correspondingly for the proper work of the functionality.'
            . ' Please consult the user guide to find additional details.'
        )
    ); ?>
</div>
