<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_GiftCard
*/
?>
<?php /** @var \Amasty\GiftCard\Block\Adminhtml\System\Config\InformationBlocks\ImagickNotification $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<div>
    <p class="message message-notice">
        <?= $escaper->escapeHtml($block->getNotificationText()); ?>
    </p>
</div>
