<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_GiftCard
*/
?>
<?php
/**
 * @var $block Amasty\GiftCard\Block\Product\View\Type\GiftCard
 * @var $escaper Magento\Framework\Escaper
 */

$product = $block->getProduct();
$productId = $product->getId();
?>

<!-- ko scope: 'giftCard_<?= $escaper->escapeHtml($productId) ?>' -->
<div class="amcard-general-container" data-amcard-js="giftcard-container" data-bind="css: {'-visible': isContainerReady}">
    <!-- ko if: giftCardType == cardTypes.combined -->
    <div class="amcard-form-container">
        <span class="amcard-title"><?= $escaper->escapeHtml(__('Want to send a physical gift card or prefer to keep things digital?')) ?></span>
        <div class="amcard-flex-container -checkbox">
            <div class="amcard-checkbox-container">
                <input type="checkbox"
                       id="amcard-checkbox-physical"
                       class="amcard-checkbox"
                       data-bind="checked: isPhysicalGift, checkedValue: 2, css: {'required-entry': !currentCardType()}" />
                <label for="amcard-checkbox-physical" class="amcard-label">
                    <span class="amcard-name"><?= $escaper->escapeHtml(__('Physical Gift Card')) ?></span>
                </label>
            </div>
            <div class="amcard-checkbox-container">
                <input type="checkbox"
                       id="amcard-checkbox-egift"
                       class="amcard-checkbox"
                       data-bind="checked: isEGift, checkedValue: 1, css: {'required-entry': !currentCardType()}" />
                <label for="amcard-checkbox-egift" class="amcard-label">
                    <span class="amcard-name"><?= $escaper->escapeHtml(__('e-Gift Card')) ?></span>
                </label>
            </div>
        </div>
        <input type="hidden"
               name="am_giftcard_type"
               class="amcard-input required-entry"
               data-bind="value: currentCardType, afterRender: getGiftCardType.bind($data, $element.name)" />
    </div>
    <!-- /ko -->
    <!-- ko if: isShowPrices -->
        <div class="amcard-form-container" data-bind="scope: 'price_<?= $escaper->escapeHtml($productId) ?>'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    <!-- /ko -->
    <div class="amcard-form-container -interior" data-bind="scope: 'images_<?= $escaper->escapeHtml($productId) ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div class="amcard-form-container">
        <div class="amcard-flex-container">
            <!-- ko if: isShowField('am_giftcard_sender_name') -->
            <div class="amcard-field-container">
                <span class="amcard-title"><?= $escaper->escapeHtml(__('Your Name')) ?></span>
                <div class="amcard-field-block">
                    <input type="text"
                           class="amcard-field required-entry"
                           name="am_giftcard_sender_name"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Enter Sender Name')) ?>"
                           data-amcard-js="field"
                           data-bind="value: getPreconfiguredValue($element.name)" />
                </div>
            </div>
            <!-- /ko -->
            <!-- ko if: isShowField('am_giftcard_recipient_name') && (!isPhysicalGift() || isEGift()) -->
            <div class="amcard-field-container">
                <span class="amcard-title"><?= $escaper->escapeHtml(__('Recipient Name')) ?></span>
                <div class="amcard-field-block">
                    <input type="text"
                           class="amcard-field required-entry"
                           name="am_giftcard_recipient_name"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Enter Recipient Name')) ?>"
                           data-amcard-js="field"
                           data-bind="value: getPreconfiguredValue($element.name)" />
                </div>
            </div>
            <!-- /ko -->
        </div>
        <!-- ko if: !isPhysicalGift() || isEGift() -->
        <span class="amcard-title"><?= $escaper->escapeHtml(__('Recipient Email')) ?></span>
        <div class="amcard-field-block">
            <input type="email"
                   class="amcard-field required-entry"
                   name="am_giftcard_recipient_email"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter Recipient Email')) ?>"
                   data-amcard-js="field"
                   data-bind="value: getPreconfiguredValue($element.name)" />
        </div>
        <!-- /ko -->
        <!-- ko if: isShowField('mobilenumber') && (!isPhysicalGift() || isEGift()) -->
            <!-- ko template: $data.phoneTemplate --><!-- /ko -->
        <!-- /ko -->
        <!-- ko if: isShowField('am_giftcard_message') -->
            <!-- ko template: $data.amGiftcardMessageTemplate --><!-- /ko -->
        <!-- /ko -->
    </div>
    <!-- ko if: isEGift() || giftCardType == cardTypes.virtual -->
    <div class="amcard-preview-container">
        <input type="button" class="amcard-button" value="<?= $escaper->escapeHtmlAttr(__('Preview Gift Card')) ?>" data-bind="click: openGiftPreview" />
        <div class="amcard-preview" data-amcard-js="preview"></div>
    </div>
    <!-- /ko -->
    <!-- ko if: isShowField('am_giftcard_date_delivery') -->
    <div class="amcard-form-container" data-bind="scope: 'datepicker_<?= $escaper->escapeHtml(__($product->getId())) ?>'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <!-- /ko -->
</div>
<!-- /ko -->
<?= $block->getChildHtml('amgc.component.price') ?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "datepicker_<?= $escaper->escapeHtml($productId) ?>": {
                    "component": "Amasty_GiftCard/js/datepicker",
                    "template": "Amasty_GiftCard/datepicker",
                    "timezones": <?= /* @noEscape */ $block->getListTimezones() ?>,
                    "preconfiguredValues": <?= /* @noEscape */ $block->getDefaultValues() ?>
                },
                "images_<?= $escaper->escapeHtml($productId) ?>": {
                    "component": "Amasty_GiftCard/js/images",
                    "template": "Amasty_GiftCard/images",
                    "images": <?= /* @noEscape */ $block->getImages() ?>,
                    "isCustomImageAllowed": <?= /* @noEscape */ (int)$block->getAllowUsersUploadImages() ?>,
                    "tooltip": "<?= $escaper->escapeHtml($block->getTooltipContent()) ?>",
                    "customImageUrl": "<?= $escaper->escapeUrl($block->getCustomImageUrl()) ?>",
                    "preconfiguredValues": <?= /* @noEscape */ $block->getDefaultValues() ?>
                },
                "giftCard_<?= $escaper->escapeHtml($productId) ?>": {
                    "component": "Amasty_GiftCard/js/giftcard",
                    "giftCardType": "<?= /* @noEscape */ $product->getAmGiftcardType() ?>",
                    "previewUrl": "<?= $escaper->escapeUrl($block->getUrl('amgcard/preview/getPreviewContent')) ?>",
                    "allowedFields": <?= /* @noEscape */ $block->getAvailableOptions() ?>,
                    "preconfiguredValues": <?= /* @noEscape */ $block->getDefaultValues() ?>,
                    "customImageUrl": "<?= $escaper->escapeUrl($block->getCustomImageUrl()) ?>",
                    "isShowPrices": "<?= /* @noEscape */ $block->isShowPrices() ?>",
                    "amEmailTemplate": "<?= /* @noEscape */ $product->getAmEmailTemplate() ?>"
                },
                "price_<?= $escaper->escapeHtml($productId) ?>": {
                    "component": "Amasty_GiftCard/js/price",
                    "template": "Amasty_GiftCard/price",
                    "prices": <?= /** @noEscape */ $block->getPredefinedAmountsJson() ?>,
                    "currencyCode": "<?= $escaper->escapeHtmlAttr($block->getCurrencyCode()) ?>",
                    "feeType": "<?= $escaper->escapeHtmlAttr($product->getAmGiftcardFeeType()) ?>",
                    "feeValue": "<?= $escaper->escapeHtmlAttr($product->getAmGiftcardFeeValue()) ?>",
                    "feeStatus": "<?= $escaper->escapeHtmlAttr($product->getAmGiftcardFeeEnable()) ?>",
                    "feeValueConverted": "<?= $escaper->escapeHtmlAttr($block->getFeeValueConverted()) ?>",
                    "productId": "<?= $escaper->escapeHtmlAttr($product->getId()) ?>",
                    "customMinAmountCurrency": "<?= /** @noEscape */ $block->convertAndFormatCurrency((float)$product->getAmOpenAmountMin(), false) ?>",
                    "customMaxAmountCurrency": "<?= /** @noEscape */ $block->convertAndFormatCurrency((float)$product->getAmOpenAmountMax(), false) ?>",
                    "customMinAmount": "<?= $escaper->escapeHtmlAttr($block->convertAndRoundCurrency((float)$product->getAmOpenAmountMin())) ?>",
                    "customMaxAmount": "<?= $escaper->escapeHtmlAttr($block->convertAndRoundCurrency((float)$product->getAmOpenAmountMax())) ?>",
                    "isOpenAmount": "<?= $escaper->escapeHtmlAttr((bool)$product->getAmAllowOpenAmount()) ?>",
                    "isSinglePrice": "<?= /* @noEscape */ $block->isSinglePrice() ?>"
                }
            }
        }
    }
}
</script>
