<?php
$_helper = $this->helper('TiDesign\Videobackground\Helper\Data');
if($_helper->checkDisabled() == false){
	$liste = $_helper->getCollection();
	$debugMode = $_helper->getDebugMode();
	if($debugMode==1){
	?>
		<style>
			.debug_panel{
				background:#fff;
				padding:20px 10px;
				color:#000 !important
			}
			.debug_panel strong{
				min-width: 100px;
				display: inline-block;
			}
		</style>
		<div class='container' style="position: relative;"><div class='debug_panel'>
		<h4>Video Background Debug Informations</h4>
		

		
		
	<?php
	}
	if($liste){
	if ($liste["qty"]>0){
		$mediaUrl = $_helper->getMediaUrl();
		$item = $liste["data"]->getFirstItem();
		
		if($item['video_source'] == 0){
			$videoId 	= $_helper->getVideoId($item->getVideoUrl());
		}
		
			
			$videoLoop	= $item->getVideoLoop();
			
			if($debugMode==1){	
					echo "<strong>Source:</strong>".$item['video_source']."<br>";
					echo "<strong>Reaseon:</strong>".$liste["source"]."<br>";
					echo "<strong>Store Id:</strong>".$_helper->getCurrentStore()->getId()."<br>";
					echo "<strong>Record Id:</strong>".$item->getId()."<br>";
					if($item['video_source'] == 0){
						echo "<strong>Video Url:</strong> Youtube : ".$item->getVideoUrl()."<br>";
						echo "<strong>Video Id:</strong>".$videoId."<br>";
					}else{
						
					}
					echo "<strong>Loop Video:</strong>".(boolval($videoLoop) ? 'true' : 'false')."<br>";
					echo "<br><strong>Controller Module Name:</strong>".$_helper->getController()."<br>";
					echo "<br><strong>Disabled List</strong><pre>";
					foreach ($_helper->getDisabled() as $d){
						echo $d."<br>";
					}
					echo "</pre><br>";					
			}
						
	?>
	<script>
	require([
		'jquery'
	], function ($) {
		'use strict';
		$(document).ready(function(){
//			console.log("başla");

<?php 
	if($item['video_source'] == 1){
?>	
			var bbody = $('body');
			var tubularContainer = '<div id="tubular-container" style="overflow: hidden; position: fixed; width: 100%; height: 100%"><video autoplay muted loop id="myVideo" style="object-fit: fill;width: 100%;height: 100%;"><source src="<?php echo  $mediaUrl;?>TiDesign/videobackground/nzboxer_video.webm" type="video/webm"> <source src="<?php echo  $mediaUrl;?>TiDesign/videobackground/nzboxer_video.mp4" type="video/mp4">Your browser does not support HTML5 video.</video></div>';				
			$('html').css({'width': '100%', 'height': '100%'});
			bbody.prepend(tubularContainer);
			bbody.css({position: 'relative', 'z-index': 99});
<?php	
	}else{
?>
			var tag = document.createElement('script');
			tag.src = "//www.youtube.com/iframe_api";
			var firstScriptTag = document.getElementsByTagName('script')[0];
			firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

			var options = {
				ratio: 16/9, // usually either 4/3 or 16/9 -- tweak as needed
				videoId: '<?php echo $videoId;?>', // toy robot in space is a good default, no?
				mute: 'true',
				repeat:<?php echo (boolval($videoLoop) ? 'true' : 'false');?>,
				width: $(window).width(),
				wrapperZIndex: 99,
				playButtonClass: 'tubular-play',
				pauseButtonClass: 'tubular-pause',
				muteButtonClass: 'tubular-mute',
				volumeUpClass: 'tubular-volume-up',
				volumeDownClass: 'tubular-volume-down',
				increaseVolumeBy: 10,
				start: 0
			};


				var bbody = $('body');
				var tubularContainer = ' <!-- Google Tag Manager (noscript) --><noscript><iframe  src="https://www.googletagmanager.com/ns.html?id=GTM-MCCB6LJ2" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><!-- End Google Tag Manager (noscript) --> <div id="tubular-container" style="overflow: hidden; position: fixed; width: 100%; height: 100%"><div id="tubular-player" style="position: absolute"></div></div><div id="tubular-shield" style="width: 100%; height: 100%;  position: absolute; left: 0; top: 0;"></div>';
				$('html').css({'width': '100%', 'height': '100%'});
				bbody.prepend(tubularContainer);
				bbody.css({position: 'relative', 'z-index': options.wrapperZIndex});

				var player;
				window.player;
				window.onYouTubeIframeAPIReady = function() {
					player = new YT.Player('tubular-player', {
						width: options.width,
						height: Math.ceil(options.width / options.ratio),
						videoId: options.videoId,
						host: 'https://www.youtube-nocookie.com',
						playerVars: {
							controls: 0,
							showinfo: 0,
							modestbranding: 1,
							wmode: 'transparent',
							autoplay: 1,
							loop: <?php echo $videoLoop;?>,
							playlist: options.videoId,
							rel: 0
						},
						events: {
							'onReady': onPlayerReady,
							'onStateChange': function(event){
								//console.log(event.data);
								if (event.data == 0) {
									//console.log("bitti");
								}
							}
						}
					});
				}





				// resize handler updates width, height and offset of player after resize/init
				var resize = function() {
					var width = $(window).width(),
						pWidth, // player width, to be defined
						height = $(window).height(),
						pHeight, // player height, tbd
						$tubularPlayer = $('#tubular-player');

					// when screen aspect ratio differs from video, video must center and underlay one dimension

					if (width / options.ratio < height) { // if new video height < window height (gap underneath)
						pWidth = Math.ceil(height * options.ratio); // get new player width
						$tubularPlayer.width(pWidth).height(height).css({left: (width - pWidth) / 2, top: 0}); // player width is greater, offset left; reset top
					} else { // new video width < window width (gap to right)
						pHeight = Math.ceil(width / options.ratio); // get new player height
						$tubularPlayer.width(width).height(pHeight).css({left: 0, top: (height - pHeight) / 2}); // player height is greater, offset top; reset left
					}

				}
				
				window.onPlayerReady = function(e) {
					resize();
					if (options.mute) e.target.mute();
					e.target.seekTo(options.start);
					e.target.playVideo();
					e.target.setLoop(options.repeat);
				}

				$(window).on('resize', function(){
					resize();
				});
<?php
	}
?>	
				
		})
	})
	</script>
	<?php
	}
	}
	if($debugMode==1){	
	 
/*	
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');

echo $request->getRouteName() . '<br />';
echo $request->getModuleName() . '<br />';
echo $request->getControllerName() . '<br />';
echo $request->getActionName() . '<br />';
echo $request->getFullActionName() . '<br />';
echo $request->getControllerModule() . '<br />';	
*/




		echo "</div ></div>";
	}

}

?>