<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Image Optimizer UI for Magento 2 (System)
 */
/** @var \Amasty\ImageOptimizer\Block\Adminhtml\Settings\ClearFoldersButton $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="amoptimizer-clear-container" data-bind="scope: 'clear-button'">
    <!-- ko if: message -->
    <p class="amoptimizer-message" data-bind="css: {'-error': isError, '-show': message}, text: message"></p>
    <!-- /ko -->
    <button class="amoptimizer-clear" data-bind="click: submitCheckboxes"><?= $escaper->escapeHtml(__('Clear')) ?></button>
</div>

<script type="text/x-magento-init">
{
"*": {
    "Magento_Ui/js/core/app": {
            "components": {
                "clear-button": {
                    "component": "Amasty_ImageOptimizerUi/js/clear-button",
                    "submitUrl": "<?= /** @noEscape */ $block->getActionUrl() ?>"
                }
            }
        }
    }
}
</script>

