<?php
/**
 * Copyright © eComBricks. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php $blockWrapper = $block->getWrapper(); ?>
<?php $blockWrapper->setObject($block); ?>

<?php $productMetadataHelper = $this->helper(\Ecombricks\Common\Helper\ProductMetadata::class); ?>
<?php $taxHelper = $this->helper(\Magento\Tax\Helper\Data::class); ?>
<?php $quote = $block->getQuote(); ?>
<?php $address = $block->getAddress(); ?>
<?php $isVirtual = $quote->isVirtual(); ?>
<?php $groupedShippingRates = $address->getGroupedAllShippingRates(); ?>
<?php if ($groupedShippingRates) : ?>

<?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
<div id="order-shipping-method-choose" class="control">
<?php else : ?>
<div id="order-shipping-method-choose" class="control" style="display:none">
<?php endif; ?>
    
    <?php foreach ($groupedShippingRates as $sourceCode => $sourceShippingRates) : ?>
    <dl class="source">
        <dt class="source-info"><span class="source-name"><?= $block->escapeHtml($blockWrapper->getSourceName((string) $sourceCode)) ?></span></dt>
        <dd class="source-shipping-methods">
            <dl class="admin__order-shipment-methods">
                <?php foreach ($sourceShippingRates as $carrierCode => $carrierShippingRates) : ?>
                <dt class="admin__order-shipment-methods-title"><?= $block->escapeHtml($blockWrapper->getSourceCarrierName((string) $sourceCode, $carrierCode)) ?></dt>
                <dd class="admin__order-shipment-methods-options">
                    <ul class="admin__order-shipment-methods-options-list">
                        <?php foreach ($carrierShippingRates as $shippingRate) : ?>
                        <?php $shippingMethod = $shippingRate->getCode() ?>
                        <li class="admin__field-option">
                            <?php if ($shippingRate->getErrorMessage()) : ?>
                            <div class="messages">
                                <div class="message message-error error"><div><?= $block->escapeHtml($shippingRate->getErrorMessage()) ?></div></div>
                            </div>
                            <?php else : ?>
                            <?php $elementId = 's_method_'.$sourceCode.'_'.$shippingMethod; ?>
                            
                            <?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
                            <?php $attributes = 'name="order[shipping_method]['.$sourceCode.']" type="radio"' ?>
                            <?= $secureRenderer->renderEventListenerAsTag('onclick', "order.setSourceShippingMethod(\''.$sourceCode.'\', this.value)", 'input#'.$block->escapeHtmlAttr($elementId)) ?>
                            <?php else : ?>
                            <?php $attributes = 'name="order[shipping_method]['.$sourceCode.']" type="radio" onclick="order.setSourceShippingMethod(\''.$sourceCode.'\', this.value)"' ?>
                            <?php endif; ?>
                            
                            <?php $checked = ($shippingMethod === $blockWrapper->getShippingMethod($address, (string) $sourceCode)) ? 'checked="checked"' : '' ?>
                            <input <?= $attributes ?> value="<?= $shippingMethod ?>" id="<?= $elementId ?>" <?= $checked ?> class="admin__control-radio required-entry"/>
                            <label class="admin__field-label" for="<?= $elementId ?>">
                                <?= $block->escapeHtml($shippingRate->getMethodTitle() ? $shippingRate->getMethodTitle() : $shippingRate->getMethodDescription()) ?> -
                                <strong>
                                    <?php $priceExclTax = $block->getShippingPrice($shippingRate->getPrice(), $taxHelper->displayShippingPriceIncludingTax()); ?>
                                    <?php $priceInclTax = $block->getShippingPrice($shippingRate->getPrice(), true); ?>
                                    <?= $priceExclTax ?>
                                    <?php if ($taxHelper->displayShippingBothPrices() && $priceInclTax != $priceExclTax) : ?>
                                        (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= $priceInclTax ?>)
                                    <?php endif; ?>
                                </strong>
                            </label>
                            <?php endif ?>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </dd>
                <?php endforeach; ?>
            </dl>
        </dd>
    </dl>
    <?php endforeach; ?>
</div>
<?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
<?= $secureRenderer->renderStyleAsTag("display:none", 'div#order-shipping-method-choose') ?>
<?php endif; ?>
    
<?php $shippingMethods = $address->getShippingMethod(); ?>
<?php if (!empty($shippingMethods)) : ?>
<div id="order-shipping-method-info" class="order-shipping-method-info">
    <?php foreach ($shippingMethods as $sourceCode => $shippingMethod) : ?>
    <?php $shippingRate = $blockWrapper->getShippingRateByCode($address, $sourceCode, $shippingMethod); ?>
    <?php if (empty($shippingRate)) { continue; } ?>
    <?php ?>
    <dl class="source">
        <dt class="source-info"><span class="source-name"><?= $block->escapeHtml($blockWrapper->getSourceName($sourceCode)) ?></span></dt>
        <dd class="source-shipping-methods">
            <dl class="admin__order-shipment-methods">
                <dt class="admin__order-shipment-methods-title"><?= $block->escapeHtml($blockWrapper->getSourceCarrierName($sourceCode, $shippingRate->getCarrier())) ?></dt>
                <dd class="admin__order-shipment-methods-options">
                    <?= $block->escapeHtml($shippingRate->getMethodTitle() ? $shippingRate->getMethodTitle() : $shippingRate->getMethodDescription()) ?> -
                    <strong>
                        <?php $priceExclTax = $block->getShippingPrice($shippingRate->getPrice(), $taxHelper->displayShippingPriceIncludingTax()); ?>
                        <?php $priceInclTax = $block->getShippingPrice($shippingRate->getPrice(), true); ?>
                        <?= $priceExclTax ?>
                        <?php if ($taxHelper->displayShippingBothPrices() && $priceInclTax != $priceExclTax) : ?>
                            (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= $priceInclTax ?>)
                        <?php endif; ?>
                    </strong>
                </dd>
            </dl>
        </dd>
    </dl>
    <?php endforeach; ?>
    
    <?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
    <a href="#" class="action-default"><span><?= $block->escapeHtml(__('Click to change shipping method')) ?></span></a>
    <?php else : ?>
    <a href="#"
       onclick="$('order-shipping-method-info').hide(); $('order-shipping-method-choose').show(); return false"
       class="action-default"><span><?= $block->escapeHtml(__('Click to change shipping method')) ?></span></a>
    <?php endif; ?>
       
</div>

<?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
<?= $secureRenderer->renderEventListenerAsTag(
    'onclick',
    "$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();event.preventDefault()",
    'div#order-shipping-method-info a.action-default'
) ?>
<?php endif; ?>
    
<?php else : ?>
    
<?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?> 
<?php $scriptString = <<<script
require(['prototype'], function(){
    $('order-shipping-method-choose').show();
});
script;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else : ?>
<script>
require(['prototype'], function() {
    $('order-shipping-method-choose').show();
});
</script>
<?php endif; ?>

<?php endif; ?>

<?php elseif ($block->getIsRateRequest()): ?>
<div class="order-shipping-method-summary">
    <strong class="order-shipping-method-not-available"><?= $block->escapeHtml(__('Sorry, no quotes are available for this order.')) ?></strong>
</div>
<?php else: ?>
<div id="order-shipping-method-summary" class="order-shipping-method-summary">
    
    <?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?> 
    <a href="#" class="action-default"><span><?= $block->escapeHtml(__('Get shipping methods and rates')) ?></span></a>
    <?php else : ?>
    <a href="#" onclick="order.loadShippingRates();return false" class="action-default"><span><?= $block->escapeHtml(__('Get shipping methods and rates')) ?></span></a>
    <?php endif; ?>
    
    <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
</div>

<?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
<?= $secureRenderer->renderEventListenerAsTag(
    'onclick',
    "order.loadShippingRates();event.preventDefault();",
    'div#order-shipping-method-summary a.action-default'
) ?>
<?php endif; ?>

<?php endif; ?>

<div style="display: none;" id="shipping-method-overlay" class="order-methods-overlay"><span><?= $block->escapeHtml(__('You don\'t need to select a shipping method.')) ?></span></div>

<?php /* if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
<div id="shipping-method-overlay" class="order-methods-overlay"><span><?= $block->escapeHtml(__('You don\'t need to select a shipping method.')) ?></span></div>
<?= $secureRenderer->renderStyleAsTag("display: none;", 'div#shipping-method-overlay') ?>
<?php else : ?>
 * <div style="display: none;" id="shipping-method-overlay" class="order-methods-overlay"><span><?= $block->escapeHtml(__('You don\'t need to select a shipping method.')) ?></span></div>
<?php endif; */ ?>

<?php if (version_compare($productMetadataHelper->getVersion(), '2.4.0', '>=')) : ?>
<?php $scriptString = <<<script
    require(["Magento_Sales/order/create/form"], function(){
script;
$scriptString .= "order.overlay('shipping-method-overlay', ".($isVirtual ? 'false' : 'true').');'.PHP_EOL;
$scriptString .= "order.overlay('address-shipping-overlay', " . ($isVirtual ? 'false' : 'true').');'.PHP_EOL;
$scriptString .= "order.isOnlyVirtualProduct = " . ($isVirtual ? 'true' : 'false').';'.PHP_EOL;
$scriptString .= "order.setSourceCodes(".$blockWrapper->getSourceCodesJson().");".PHP_EOL;
$scriptString .= "order.setShippingMethods(".$blockWrapper->getShippingMethodsJson().");".PHP_EOL;
$scriptString .= <<<script
    });
script;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else : ?>
<script>
require(["Magento_Sales/order/create/form"], function() {
    order.overlay('shipping-method-overlay', <?php if ($isVirtual) : ?>false<?php else: ?>true<?php endif; ?>);
    order.overlay('address-shipping-overlay', <?php if ($isVirtual) : ?>false<?php else: ?>true<?php endif; ?>);
    order.isOnlyVirtualProduct = <?= $isVirtual ? 'true' : 'false'; ?>;
    order.setSourceCodes(<?= $blockWrapper->getSourceCodesJson() ?>);
    order.setShippingMethods(<?= $blockWrapper->getShippingMethodsJson() ?>);
});
</script>
<?php endif; ?>